import fs from 'fs/promises';
import path from 'path';
import type { FeatureCollection, Feature, Geometry } from 'geojson';
import type { CacheFile } from '../ingest/cache.js';

const CACHE_DIR = path.resolve('cache');
const CATALOG_DIR = path.resolve('catalog');
const CATALOG_FILE = path.join(CATALOG_DIR, 'CATALOG.md');

interface FieldSummary {
  name: string;
  types: Set<string>;
  nullCount: number;
  totalCount: number;
  examples: Set<string>;
}

function jsType(value: unknown): string {
  if (value === null || value === undefined) return 'null';
  if (Array.isArray(value)) return 'array';
  return typeof value;
}

function analyseFeatures(features: Feature[]): {
  geometryTypes: Map<string, number>;
  nullGeometryCount: number;
  fields: Map<string, FieldSummary>;
} {
  const geometryTypes = new Map<string, number>();
  let nullGeometryCount = 0;
  const fields = new Map<string, FieldSummary>();

  for (const feature of features) {
    // Geometry
    if (!feature.geometry) {
      nullGeometryCount++;
    } else {
      const gt = (feature.geometry as Geometry).type;
      geometryTypes.set(gt, (geometryTypes.get(gt) ?? 0) + 1);
    }

    // Properties
    const props = feature.properties ?? {};
    for (const [key, value] of Object.entries(props)) {
      if (!fields.has(key)) {
        fields.set(key, {
          name: key,
          types: new Set(),
          nullCount: 0,
          totalCount: 0,
          examples: new Set(),
        });
      }
      const summary = fields.get(key)!;
      summary.totalCount++;
      const t = jsType(value);
      summary.types.add(t);
      if (t === 'null') {
        summary.nullCount++;
      } else if (summary.examples.size < 5 && value !== '') {
        summary.examples.add(String(value).slice(0, 60));
      }
    }
  }

  // Account for features missing a field entirely (treat as null)
  for (const summary of fields.values()) {
    const missing = features.length - summary.totalCount;
    summary.nullCount += missing;
    summary.totalCount = features.length;
  }

  return { geometryTypes, nullGeometryCount, fields };
}

function formatNullRate(summary: FieldSummary): string {
  const rate = (summary.nullCount / summary.totalCount) * 100;
  return `${rate.toFixed(0)}%`;
}

function renderLayer(
  name: string,
  source: string,
  fetchedAt: string,
  features: Feature[],
): string {
  const { geometryTypes, nullGeometryCount, fields } = analyseFeatures(features);

  const geomSummary = geometryTypes.size === 0
    ? 'none'
    : [...geometryTypes.entries()].map(([t, n]) => `${t} (${n})`).join(', ');

  const fieldRows = [...fields.values()]
    .map((f) => {
      const types = [...f.types].filter((t) => t !== 'null').join(', ') || 'null';
      const examples = [...f.examples].map((e) => `\`${e}\``).join(', ') || '—';
      return `| ${f.name} | ${types} | ${formatNullRate(f)} | ${examples} |`;
    })
    .join('\n');

  return `## Layer: ${name}
- **Source:** ${source}
- **Fetched at:** ${fetchedAt}
- **Feature count:** ${features.length}
- **Geometry types:** ${geomSummary}
- **Null geometry count:** ${nullGeometryCount}

### Fields
| Field | Type | Null rate | Example values |
|---|---|---|---|
${fieldRows}

### Anomalies
_To be filled in manually after reviewing the data above._

### Open Questions Resolved
_To be filled in manually._

---
`;
}

async function loadCache(filename: string): Promise<{ source: string; fetchedAt: string; features: Feature[] }> {
  const raw = await fs.readFile(path.join(CACHE_DIR, filename), 'utf-8');
  const cache = JSON.parse(raw) as CacheFile<FeatureCollection>;
  return {
    source: cache.source,
    fetchedAt: cache.fetchedAt,
    features: cache.data.features,
  };
}

export async function runCataloguing(): Promise<void> {
  await fs.mkdir(CATALOG_DIR, { recursive: true });

  const layers: Array<{ name: string; file: string }> = [
    { name: 'dil_land_assets_lean_to (ArcGIS)',  file: 'arcgis_lean_tos.json' },
    { name: 'dil_reference — Park Boundary (ArcGIS)', file: 'arcgis_park_boundary.json' },
    { name: 'GNIS Water Features',                   file: 'arcgis_water_features.json' },
    { name: 'Primitive Campsites (ArcGIS)',        file: 'arcgis_campsites.json' },
    { name: 'Parking (ArcGIS)',                   file: 'arcgis_parking.json' },
  ];

  const sections: string[] = [
    '# Data Catalog\n\nAuto-generated by the cataloguing stage. Anomalies and resolved open questions filled in manually.\n\n---\n',
  ];

  for (const { name, file } of layers) {
    console.log(`  Cataloguing ${name}...`);
    const { source, fetchedAt, features } = await loadCache(file);
    sections.push(renderLayer(name, source, fetchedAt, features));
  }

  await fs.writeFile(CATALOG_FILE, sections.join('\n'));
  console.log(`  Catalog written to catalog/CATALOG.md`);
}
